#!/bin/bash

yay -S --needed --norebuild --nouseask --noredownload --noconfirm --batchinstall \
  act \
  asciinema \
  atool \
  bat \
  bcal-git \
  bmon \
  bookworm \
  buf-bin \
  cheat \
  cloc \
  ctags \
  diff-so-fancy \
  elinks \
  fd \
  ffmpegthumbnailer \
  firefox \
  g810-led-git \
  git \
  git-extras \
  git-open-git \
  git-quick-stats \
  github-cli \
  google-cloud-sdk \
  grpcurl \
  gtop \
  hexcurse-git \
  highlight \
  howdoi \
  http-prompt \
  httpie \
  httplab \
  jdk11-graalvm-bin \
  jdk11-openjdk \
  jq \
  lazygit \
  libcaca \
  mediainfo \
  mtr \
  nano-syntax-highlighting \
  ncdu \
  nmap \
  npm \
  nodejs-git-stats \
  odt2txt \
  openjdk11-src \
  poppler \
  protobuf-go \
  python-chardet \
  ranger \
  ripgrep \
  the_silver_searcher \
  tldr \
  tmux \
  unzip \
  virtualbox \
  youtube-dl \
  yq \
  woof \
  wttr \
  wuzz

for kernel in $(mhwd-kernel -li | grep " linux" | awk '{print $2}')
do
  yes | yay -S $kernel-virtualbox-host-modules
done
