#!/bin/bash

export GOPATH=~/.go

install_packages()
{
  if [ -f "$1.md5" ]; then
    md5sum -c $1.md5
    if [ $? -eq 0 ]
    then
      echo "Not updating packages as '$1' hasn't changed"
    else
      $1
      md5sum $1 > $1.md5
    fi
  else
      $1
      md5sum $1 > $1.md5
  fi
}

install_packages ~/.config/yadm/bootstrap-packages
install_packages ~/.config/yadm/bootstrap-packages-misc
install_packages ~/.config/yadm/bootstrap-packages-containers
install_packages ~/.config/yadm/bootstrap-packages-gui

~/.config/yadm/bootstrap-vscode

sudo vboxreload

sudo systemctl enable docker.service
sudo systemctl enable sshd.service

sudo gpasswd -a $USER vboxusers
sudo gpasswd -a $USER docker

# Nextcloud instead
[[ -d ~/Desktop ]] && rmdir ~/Desktop
[[ -d ~/Documents ]] && rmdir ~/Documents
[[ -d ~/Music ]] && rmdir ~/Music
[[ -d ~/Pictures ]] && rmdir ~/Pictures
[[ -d ~/Public ]] && rmdir ~/Public
[[ -d ~/Templates ]] && rmdir ~/Templates
[[ -d ~/Videos ]] && rmdir ~/Videos

[[ "$SHELL" == "/bin/zsh" ]] && echo "Shell is already zsh" || chsh -s /bin/zsh

betterlockscreen -u ~/.wallpapers/wallpaper.png

git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"

yadm submodule update --init --recursive

# Invoke the post_pull hook as the initial clone doesn't run post hooks
~/.config/yadm/hooks/post_pull
