#!/bin/bash

yay -S --needed --norebuild --nouseask --noredownload --noconfirm --batchinstall \
  dive \
  docker \
  docker-compose \
  dockly \
  fluxctl-bin \
  helm \
  istio-bin \
  rancher-k3d-beta-bin \
  k9s \
  krew-bin \
  kube-score \
  kubebox \
  kubectx \
  kubespy \
  kubetail \
  lens-bin \
  minikube-bin \
  operator-sdk \
  popeye
