#!/bin/bash

if [ $1 != "connectivity-change" ]; then
  exit
fi

if grep -q 127.0.0.1 /etc/resolv.conf; then
  exit
fi

DNS_SERVERS=`cat /etc/resolv.conf |grep -i '^nameserver'|cut -d ' ' -f2 | tr "\n" ","`
DNS_SERVERS="${DNS_SERVERS// /,}"
pihole -a setdns $DNS_SERVERS

sed -i '/^nameserver/d' /etc/resolv.conf
echo "nameserver 127.0.0.1" | tee -a /etc/resolv.conf
