#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Update submodules"
yadm submodule update --recursive --remote

direnv allow ~/Env/minikube

BASEDIR=$(dirname "$0")
if ! grep -q git@github.com:dliraf "$HOME/.config/yadm/repo.git/config"; then
  exit
fi

# SSH access to my repo. I.e me so pull in some private dotfiles as well

# No support for optional submodules in Git so clone and link instead
if [ -d "~/.dotfiles-private" ] 
then
  cd ~/.dotfiles-private
  git pull
  cd -
else
  git clone git@github.com:dliraf/dotfiles-private.git ~/.dotfiles-private
fi

if [ ! -f ~/Env/gcp/.envrc ]; then
  ln -s ~/.yadm-private/Env/gcp/.envrc ~/Env/gcp/.envrc
  direnv allow ~/Env/gcp/.envrc
fi

